### ISSUE TITLE
Application only shows notifications if app is open on iOS

### ISSUE THREAD

**Issue by cpvickery** [Telerik-Verified-Plugins/LocalNotification#1]
Hello,

I've been testing your plugin in my telerik mobile app, and have a process that runs every x minutes to check for new items that need attention.  When running the application on an android tablet, the notifications are created even if I am not in the app (app is still running in the background).  But on my iPad, the notifications are not created unless I have the application open.  In settings on the iPad, I have Notifications enabled for the app.  Is this just a limitation when running on an iOS device, or should it behave the same in both environments?

Thanks,

Chris Vickery

![img_0007](https://cloud.githubusercontent.com/assets/8989224/4482696/f2ca6846-49aa-11e4-80e0-1cde2a2f38ff.jpg)

**Comment by slightlydiff** [comment]
Same issue.  I need the local notification to run some code in the app on trigger but the trigger event doesn't seem to work in IOS when the app is in the background.  Does anyone know how to get this working or of an alternative plugin that may achieve this?

**Comment by EddyVerbruggen** [comment]
Works fine with [our demo app](https://github.com/Telerik-Verified-Plugins/LocalNotification-DemoApp) and version 0.8.4 of the plugin. Please reopen if that proofs false on your end (but also provide a sample app which can be used to reproduce the issue).
