### ISSUE TITLE
On iOS 9 the plugin freezes app

### ISSUE THREAD

**Issue by ghost** [Telerik-Verified-Plugins/LocalNotification#11]
I upgraded my iPhones and Xcode over the weekend to iOS 9 and now my app freezes as soon as notification is scheduled like:

``` javascript
cordova.plugins.notification.local.schedule({
                id        : Math.floor(Math.random() * 1000),
                title     : 'Parking Meter',
                text      : 'Your parking meter time expires soon!',
                every     : 'minute',
                //autoClear : true,
                at        : new Date(new Date().getTime() + duration*60*1000)
            });
```

Xcode jumps to APPLocationNotificationOptions.m line 142 EXC_BAD_ACCESS ...

Anyone else with the same issue?

Same code still working as expected on Samsung 6 Edge with Android 5.0.2.

**Comment by EddyVerbruggen** [comment]
Taking a look, thanks!

**Comment by EddyVerbruggen** [comment]
Hi @bardu, thanks again for letting us know. 0.8.2dev3 fixes the issue.

**Comment by ghost** [comment]
Thanks for the quick fix!

**Comment by marcvanh** [comment]
Thanks for the fix, however now the app is freezing in a different spot:

Xcode jumps to UIApplication+APPLocalNotification.m, line 1919, SIGABRT

**Comment by EddyVerbruggen** [comment]
@bardu do you have the same problem?
@marcvanh that's a strange line number, since the class is only 331 lines long..

**Comment by marcvanh** [comment]
Sorry - it's line 191

```
    if ([notification.options.id isEqualToNumber:id]) {
```

**Comment by EddyVerbruggen** [comment]
Thanks @marcvanh, did you set an ID like in @bardu's example?

**Comment by marcvanh** [comment]
In case it helps, it is happening on a cancel() call, and the id passed may not exist. I haven't tested other calls.

**Comment by marcvanh** [comment]
There would have been an id, but it may have never been a valid notification. It's a catch-all cancel that always worked prior to iOS 9

**Comment by EddyVerbruggen** [comment]
Thanks for clearing that up - ideas for a fix as well perhaps?

**Comment by marcvanh** [comment]
No, sorry I am not too familiar with Obj C

**Comment by EddyVerbruggen** [comment]
If you can, please try this instead of the current line 191 - guessing the id is nil..:

```
        if (notification.options.id != nil && [notification.options.id isEqualToNumber:id]) {
```

**Comment by marcvanh** [comment]
Just tested - the value was actually not nil - it was a real notification id.

**Comment by EddyVerbruggen** [comment]
I don't think I can help you since I can't reproduce it..

**Comment by marcvanh** [comment]
Have you tried it with a non-existent notification id?

**Comment by EddyVerbruggen** [comment]
Is there a way to create one that you know of?
