### ISSUE TITLE
Not working on iOS 9.1

### ISSUE THREAD

**Issue by manuelpaulo** [Telerik-Verified-Plugins/LocalNotification#12]
On iOS 9.1, all I am getting is the cordova white screen of dead AGAIN. 
Will this happen with every new iOS release? 
Seriously considering disabling this for good. 
Had enought of having my apps being rated 1 star as they stop working every time apple updates the iOS! Always the same reason: this plugin!

```
cordova.plugins.notification.local.schedule({
     id         : 1,
     title      : 'I will bother you every minute',
     text       : '.. until you cancel all notifications',
     sound      : null,
     every      : 'minute',
     autoClear  : false,
     at         : new Date(new Date().getTime() + 10*1000)
     });

```

**Comment by EddyVerbruggen** [comment]
Have you tried opening an issue at the [upstream repository](https://github.com/katzer/cordova-plugin-local-notifications)? That's where most users of this plugin are.

That being said, if you like I can take a look at your project. If so, please send me your project and tell me how to reproduce this problem (I have an iOS 9.1 6 and 6S).

**Comment by manuelpaulo** [comment]
This fork works: https://github.com/NorthMcCormick/cordova-plugin-local-notifications

**Comment by EddyVerbruggen** [comment]
Have you tried the latest release of this repo as well? It seems I did [a similar fix](https://github.com/Telerik-Verified-Plugins/LocalNotification/commit/c94c6d5c3d330f881fdd17b0a411714c4e1c03ce) as the fork you mentioned.

**Comment by manuelpaulo** [comment]
I think I will give up on using this plug-in. There's a 99% chance it will make my apps broken again when Apple releases version 9.2.

**Comment by EddyVerbruggen** [comment]
Perhaps it will. I don't know your usecase, maybe the Calendar plugin is a good alternative?
Anyway, afaik the latest version of this plugin should be fine.

**Comment by closdesign** [comment]
Did this ever get working in iOS 9?  We have this plugin in our app and in iOS 9.1 on iPhone 6S it does not fire a notification outside of the app.  Only until I actually launch the app is when the notification fires.
Android seems to work as expected.
Our AppBuilder project says we are using version 8.2.

**Comment by EddyVerbruggen** [comment]
Hi @closdesign I didn't have an issue but updated to 0.8.4 (from the upstream) anyway. Tested again and all looks fine. I've confirmed it works fine outside the app and after a reboot [with our demo app](https://github.com/Telerik-Verified-Plugins/LocalNotification-DemoApp).

**Comment by closdesign** [comment]
Hi Eddy,

We will take a look at example.  I can post a bit of code that we are using for our call. Thanks for responding.
