### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by masterofdaemon** [Telerik-Verified-Plugins/LocalNotification#13]
here is my install command: 
cordova plugin add https://github.com/Telerik-Verified-Plugins/LocalNotification#0.8.2dev4

this is error output:  
problem occurred configuring root project 'android'.

> Could not resolve all dependencies for configuration ':_debugCompile'.
> Could not find any version that matches com.android.support:support-v4:+.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
>          https://repo1.maven.org/maven2/com/android/support/support-v4/
>      Required by:
>          :android:unspecified

**Comment by masterofdaemon** [comment]
cordova --version
5.3.3

**Comment by EddyVerbruggen** [comment]
Are you building with the Cordova CLI?
Also, what's your cordova-android version?

**Comment by masterofdaemon** [comment]
no just npm install
"android": "4.1.1"? how to know?

**Comment by masterofdaemon** [comment]
node 0.12, in 4.1 don't works

**Comment by ghost** [comment]
Something seems to be mixed up, when downloading the latest version. 
In Android Studio I get the error

> /home/bardu/AndroidStudioProjects/pma/platforms/android/src/de/appplant/cordova/plugin/notification/Notification.java
> Error:(34, 30) java: package android.support.v4.app does not exist
> Error:(65, 37) java: package NotificationCompat does not exist
> Error:(81, 39) java: package NotificationCompat does not exist

I tried to install dev3, which worked fine for me in another project, but this failed:

> cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.2dev3
> Fetching plugin "de.appplant.cordova.plugin.local-notification@0.8.2dev3" via cordova plugins registry
> npm http GET http://registry.cordova.io/de.appplant.cordova.plugin.local-notification/0.8.2-dev3
> npm http 404 http://registry.cordova.io/de.appplant.cordova.plugin.local-notification/0.8.2-dev3
> Fetching from cordova plugins registry failed: version not found: 0.8.2-dev3 : de.appplant.cordova.plugin.local-notification/0.8.2-dev3

Using # instead of @ like the OP downloads version 0.8.1

Can someone verify?

**Comment by masterofdaemon** [comment]
on ios it compiles fine

**Comment by slightlydiff** [comment]
I've had this issue too.  Telerik support were great and suggested to not install it from the market place but download and import it instead then open its plugin.xml file (you will find it under the Local Notifications plugin folder, under Plugins in the Project Navigator) and comment the following line:

``` javascript
    From:
    <framework src="com.android.support:support-v4:+" />
    To:
    <!--<framework src="com.android.support:support-v4:+" />-->
```

I believe a proper resolution is being looked into

**Comment by EddyVerbruggen** [comment]
If you're building with the CLI and have the latest Android support bits installed locally as well (type `android` in a Terminal window) then Cordova should be able to find the support library via Gradle.

If you're using AppBuilder then make sure you're targeting the latest Cordova version (as mentioned [here in the yellow box at the top](http://plugins.telerik.com/cordova/plugin/localnotification)) or use an older version of the plugin.

**Comment by masterofdaemon** [comment]
all new, and builds before i'm add plugin, here is the output : /test-noty/platforms/android/cordova/build 
ANDROID_HOME=/usr/local/Cellar/android-sdk/24.4.1
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
Running: /Users/serg/projs/test-noty/platforms/android/gradlew cdvBuildDebug -b /Users/serg/projs/test-noty/platforms/android/build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'android'.
  
  > Could not resolve all dependencies for configuration ':_debugCompile'.
  > Could not find any version that matches com.android.support:support-v4:+.
  >  Searched in the following locations:
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/
  >  Required by:
  >      :android:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.479 secs

/Users/serg/projs/test-noty/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Users/serg/projs/test-noty/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/serg/projs/test-noty/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/serg/projs/test-noty/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/serg/projs/test-noty/platforms/android/cordova/build: Command failed with exit code 1

**Comment by masterofdaemon** [comment]
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications" via git clone
Repository "https://github.com/katzer/cordova-plugin-local-notifications" checked out to git ref "master".
Installing "de.appplant.cordova.plugin.local-notification" for android
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" for android

```
    Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
    https://github.com/katzer/cordova-plugin-local-notifications#supporting

    Thank you!
```

**Comment by EddyVerbruggen** [comment]
I'm not sure what you've tried already, so did you perhaps Google the error "Could not find any version that matches com.android.support:support-v4:+" and tried a few of those suggestions?

**Comment by ghost** [comment]
In my case it was my bad. I switched from Eclipse to Android Studio and instead to open the project from `myproject/platforms/android` I pointed just to `myproject`.

**Comment by masterofdaemon** [comment]
yes i found solution:
"Open the SDK manager (from command line, type "android").
Under "Extras", Make sure you have "Android Support Repository" and "Google Repository" downloaded." 
Thank you all.

**Comment by EddyVerbruggen** [comment]
:+1:  Good job!
