### ISSUE TITLE
GetAll notifications issue

### ISSUE THREAD

**Issue by feruzm** [Telerik-Verified-Plugins/LocalNotification#14]
It looks there is an issue with getall method.
If I have 2 scheduled notifications, It will get 1 of them twice.

 $cordovaLocalNotification.getAll().then(function(notification) {
                            console.log(JSON.stringify(notification));
                        });

ngcordova just wraps this plugin's getall method. So there is no problem with that, I even tried with plugin method.
cordova.plugins.notification.local.getall(function (notification) {
   //output
})
still same issue.

**Comment by EddyVerbruggen** [comment]
Please retest with 0.8.4 and make sure ngCordova is not the cause.
