### ISSUE TITLE
iOS 10 support?

### ISSUE THREAD

**Issue by frigon** [Telerik-Verified-Plugins/LocalNotification#16]
I've got the same code running on a ios10 and ios9 device and notifications don't show up in the notification area in iOS 10.  Is this not supported or is it possible a bug in iOS 10?

**Comment by Scalpweb** [comment]
This plugin comes from a fork, and a PR has been sent to the initial version to fix this issue.

You can check it out here : https://github.com/katzer/cordova-plugin-local-notifications/pull/1093

So what you need to do is to remove the telerik version of the plugin from you version and add the initial one (from Katzer), then apply the fixes from the PR. It's working on my side.

**Comment by Scalpweb** [comment]
Nevermind... Not possible with Telerik, as they do not accept "10.0" as iOS target version. So it will not compile.

**Comment by Eolus** [comment]
Any progress on getting iOS 10 support added?  This has broken an important feature for iOS 10 users.

0.8.4 installs fine on iOS 10 and accepts schedule requests, but never delivers any notifications.  The [katzer ios 10 branch](https://github.com/katzer/cordova-plugin-local-notifications/tree/ios10) mentioned above will not build, so we are stuck for the moment.

**Comment by EddyVerbruggen** [comment]
That fork is for adding the new iOS 10 way of adding notifications to the plugin, _however_ the current way should work just fine as it's only deprecated and will probably work fine for a few major iOS releases to come (as with all things Apple deprecated, luckily).

So there must be something else going on and I suspect it to be the repeat interval logic as that's what I had to fix on my [NativeScript plugin](https://github.com/EddyVerbruggen/nativescript-local-notifications/commit/f81dea5d8d6e30d195b8e1fd6ce9d93f5f6d26b6) recently as well.

**Comment by EddyVerbruggen** [comment]
Fixed in 0.8.4.1. It was indeed a problem with the repeat logic which Apple changed a bit for iOS 10. Easy fix, hard to find. Also sent a PR to the Katzer upstream repo.

**Comment by Eolus** [comment]
Eddy - Thanks for the quick response - that did the trick!
