### ISSUE TITLE
Unable to create Notification

### ISSUE THREAD

**Issue by ramsabarish** [Telerik-Verified-Plugins/LocalNotification#2]
I'm using ios sdk 7.1 .  

Through CLI I Added  cordova plugin add https://github.com/Telerik-Verified-Plugins/LocalNotification

In index.js I have written 

$(document).ready(function(){

window.plugin.notification.local.add({ id  : 'myID',
                                       title      : 'I will bother you every minute',
                                       message    : '.. until you cancel all notifications',
                                       sound      : null,
                                       repeat     : 'minutely',
                                       autoCancel : false,
                                       date       : new Date(new Date().getTime() + 10*1000)
                                                       });
    });

After this no notification is created and all  other click functionalities are not working.  No error is shown   on Xcode  but i guess window.plugin.notification.local.add({})  would be undefined . Please tell me what  error I would have committed  or I need to  add something in config.xml .

**Comment by EddyVerbruggen** [comment]
Hi, one issue is that you need to wait for deviceready to fire, not document ready. I need more of your code for further assistance.
