### ISSUE TITLE
dependecy error

### ISSUE THREAD

**Issue by Danelund** [Telerik-Verified-Plugins/LocalNotification#5]
Hey, I got this error when trying to build:

```
Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
at checkID 
```

I think the dependency in plugin.xml needs to be changed to:

```
<dependency id="cordova-plugin-device" url="https://git-wip-us.apache.org/repos/asf/cordova-plugin-device.git" commit="master" subdir="." />
```

according to:

http://stackoverflow.com/questions/29945563/html5video-cordova-android-plugin-wont-install-error-using-cli

**Comment by EddyVerbruggen** [comment]
Thanks for letting us know. Which version of the CLI are you using? And which version of the plugin?
I did just try to install it myself with `cordova -v` = 5, and that worked fine.

**Comment by Danelund** [comment]
I'm using cordova 3.5.0, and I'm actually not using the CLI, I'm just relying on telerik appbuilder's built in "build" function, so maybe it's an issue with that you reckon?

plugin version 0.8.0dev3

UPDATE: changed plugin version to 0.8.0dev4, and that resolved the issue

**Comment by EddyVerbruggen** [comment]
I'm guessing you're using an older version of the plugin. Can you try removing it, create a build to verify it works again, and then re-add it?

Also, you're welcome to use Cordova 3.7.0, it's considered stable in AppBuilder currently.

Best,
Eddy

**Comment by EddyVerbruggen** [comment]
Ha, I was just too late with my comment. :+1:

**Comment by Danelund** [comment]
Thanks for taking the time to comment on this Eddy, it was a great help, to get my attention pointed in the direction of the problem :)
