### ISSUE TITLE
Changing Text dynamically

### ISSUE THREAD

**Issue by ghost** [Telerik-Verified-Plugins/LocalNotification#8]
If notification is schedule every minute is there a way to change the notification text for each subsequent notification?
For example:
Meter expires in 5 minutes
Meter expires in 4 minutes
...
Meter expires in 1 minute

**Comment by EddyVerbruggen** [comment]
Even if it was technically possible to update those local notification, your app wouldn't be able to do it simply because it's potentially not running at all.

So just schedule separate notifications instead of one if you need them to show different messages.
